- hosts: localhost
  connection: local
  remote_user: root
  sudo: yes

  vars:
  # ユーザ名とパスワードは変更可能です。
   mysql_db_user: oc_dbadmin
   mysql_db_password: owncloud
   php_timezone: Asia/Tokyo
   path_document_root: /var/www/html/owncloud

  tasks:
  - name: Install ownCloud reopsitory
  #CentOS7.x用ownCloud8.2レポジトリのインストール。
    get_url: url=http://dl.fedoraproject.org/pub/epel/7/$(uname -i)/e/epel-release-7-5.noarch.rpm
    get_url: url=http://download.owncloud.org/download/repositories/8.2/CentOS_7/ce:8.2.repo dest=/etc/yum.repos.d/

  - name: Install Apache packages
  # Apache をインストール。
    yum: name=httpd state=present

  - name: Install mod_ssl
  # mod_ssl をインストール。
    yum: name=mod_ssl state=present

  - name: Install php packages
  # PHP5.4をインストール。
    yum: name="{{ item }}" state=present
    with_items:
      - php
      - php-mbstring
      - php-pdo
      - php-mysql
      - php-xml
      - php-gd
      - php-ldap
      - php-process
      
  - name: Install MariaDB
  # MariaDBをインストール。
    yum: name="{{ item }}" state=present
    with_items:
      - mariadb-server
      - mariadb
      - mariadb-libs
      - MySQL-python

  - name: restart mariadb 
  # MariaDBの起動
    service: name=mariadb state=started

  - name: Create owncloud DB
  # ownCloudのデータベースを作成する。
    mysql_db:
     name=owncloud
  
  - name: Set DBUser and Password
    mysql_user:
     name={{ mysql_db_user }}
     password={{ mysql_db_password }}
     priv=owncloud.*:ALL

  - name: Install ownCloud
  # ownCloudのインストール。
    yum: name=owncloud state=present

  - name: Make owncloud data dir
  # ownCloud用データ領域の作成
    file: dest=/home/owncloud/data owner=apache group=apache state=directory

  - name: Change php timezone
  # phpタイムゾーンの変更
    replace: >-
      dest=/etc/php.ini
      regexp="^;date\.timezone ="
      replace="date.timezone = {{ php_timezone }}"
  - name: Change php setting 
  
  # PHPの設定変更
  # change expose_php
    replace: >-
       dest=/etc/php.ini
       regexp="^expose_php = On"
       replace="expose_php = Off"
       
    # Change php default_charset
    replace: >-
       dest=/etc/php.ini
       regexp=";default_charset ="
       replace="default_charset ="
       
  - name: Change Apache DocumentRoot
  # Apache DocumentRootの変更。
    replace: >-
       dest='/etc/httpd/conf/httpd.conf'
       regexp='^DocumentRoot .*'
       replace='DocumentRoot "{{ path_document_root }}/"'
  - name: create self signed certificate
    shell: |
       crt_file="/etc/pki/tls/certs/{{ inventory_hostname }}.crt" &&
       key_file="/etc/pki/tls/private/{{ inventory_hostname }}.key" &&
       crt_and_key_file="/etc/pki/tls/private/{{ inventory_hostname }}.crt_and_key" &&
       subject="/C=JP/CN={{ inventory_hostname }}" &&
       openssl req -new -newkey rsa:2048 -sha1 -x509 -nodes \
        -set_serial 1 \
        -days 365 \
        -subj "$subject" \
        -out "$crt_file" \
        -keyout "$key_file" &&
       cat "$crt_file" "$key_file" >> "$crt_and_key_file" &&
       chmod 400 "$key_file" "$crt_and_key_file"
       creates="/etc/pki/tls/certs/{{ inventory_hostname }}.crt"
       
  - name: change ssl document root
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^#DocumentRoot .*'
       replace='DocumentRoot "{{ path_document_root }}/"'
       
  - name: change ssl servername
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^#ServerName .*'
       replace='ServerName "{{ inventory_hostname }}"'
       
  - name: change ssl SSLProtocol
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^SSLProtocol .*'
       replace='SSLProtocol all -SSLv2 -SSLv3'
  - name: change ssl SSLCertificateFile
  
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^SSLCertificateFile .*'
       replace='SSLCertificateFile /etc/pki/tls/certs/{{ inventory_hostname }}.crt'
       
  - name: change ssl SSLCertificateKeyFile
    replace: >-
       dest='/etc/httpd/conf.d/ssl.conf'
       regexp='^SSLCertificateKeyFile .*'
       replace='SSLCertificateKeyFile /etc/pki/tls/private/{{ inventory_hostname }}.key'
       
  - name: restart httpd
  # Apacheの再起動
    service: name=httpd state=restarted enabled=yes

  - name: restart mariadb
  # MariaDBの再起動
    service: name=mariadb state=restarted enabled=yes
